apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: customer-profile
  namespace: bridget
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: customer-profile
    apis.apps.tanzu.vmware.com/register-api: "true"
    apps.tanzu.vmware.com/has-tests: "true"
spec:
  serviceClaims:
    - name: db
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ResourceClaim
        name: psql-bridget
  build:
    env:
      - name: BP_JVM_VERSION
        value: "11"
  params:
    - name: testing_pipeline_matching_labels
      value:
        apps.tanzu.vmware.com/pipeline: customer-profile-test-pipeline
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
    - name: gitops_server_address
      value: ssh://git@github.com
    - name: gitops_ssh_secret
      value: gitops-ssh
    - name: gitops_repository_owner
      value: Mpluya
    - name: gitops_repository_name
      value: config-java-rest-service-tkgs
    - name: gitops_branch
      value: main
    - name: api_descriptor
      value:
        type: openapi
        location: 
          path: "/api-docs"
        owner: maelarge
        system: maelarge
        description: yeet
  source:
    git:
      ref:
        branch: main
      url: ssh://git@github.com/Mpluya/java-rest-service-tkgs